#!/bin/bash

folder=${@: -1}

# Check for create command 
if [ "$1" == "create-project" ]; then 
    folder=${@: -1}
    command="composer $@; cp server.php htaccess $folder; cd $folder; mv htaccess .htaccess"
else
    # Remove the last argument
    set -- "${@:1:$(($#-1))}"
    command="cd $folder && composer $@;"
fi

echo "$command"
docker exec -it -u devuser php-container bash -c "$command"