version: '3.8'

services:
  php:
    build: 
      context: '.'
      args:
          uid: ${UID}
    container_name: php-container
    restart: always
    environment:
      - APP_URL=${APP_URL}
    ports:
      - "${PHP_PORT:-80}:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db  # Connect to MySQL service
      PMA_PORT: 3306
      PMA_ABS_URI: /phpmyadmin
    depends_on:
      - db
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Allows accessing the Docker host from phpMyAdmin

  node:
    image: node:16
    container_name: node-container
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
